# Generated by Django 5.2.11 on 2026-02-10 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harvest_date', models.DateField()),
                ('product_batch_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('qr_code_data', models.TextField(blank=True)),
                ('organic_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('quality_test_report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(max_length=120)),
                ('document_reference', models.CharField(max_length=255)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.cropbatch')),
            ],
        ),
        migrations.CreateModel(
            name='RetailListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distributor_margin', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retailer_margin', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_for_sale', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_listings', to='supplychain.cropbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='supplychain.retaillisting')),
            ],
        ),
        migrations.CreateModel(
            name='StakeholderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('transporter', 'Transporter'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('consumer', 'Consumer'), ('admin', 'Admin')], max_length=32)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('wallet_id', models.CharField(blank=True, max_length=255)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='retaillisting',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='supplychain.stakeholderprofile'),
        ),
        migrations.CreateModel(
            name='KYCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=255)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='kyc_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kyc_records', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to='supplychain.stakeholderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='inspection_reports/')),
                ('storage_conditions', models.TextField(blank=True)),
                ('passed', models.BooleanField(default=False)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='supplychain.cropbatch')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections_conducted', to='supplychain.stakeholderprofile')),
            ],
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_batches', to='supplychain.stakeholderprofile'),
        ),
        migrations.CreateModel(
            name='BatchSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_label', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='supplychain.cropbatch')),
                ('destination_retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_splits', to='supplychain.stakeholderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=32)),
                ('vehicle_details', models.TextField(blank=True)),
                ('driver_details', models.TextField(blank=True)),
                ('pickup_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_proof', models.FileField(blank=True, null=True, upload_to='delivery_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to='supplychain.cropbatch')),
                ('from_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transports', to='supplychain.stakeholderprofile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_transports', to='supplychain.stakeholderprofile')),
                ('to_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transports', to='supplychain.stakeholderprofile')),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_transports', to='supplychain.stakeholderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TransportLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_details', models.TextField(blank=True)),
                ('driver_details', models.TextField(blank=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_proof_reference', models.CharField(blank=True, max_length=255)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplychain.stakeholderprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.transportrequest')),
            ],
        ),
    ]
