# Generated by Django 5.2.10 on 2026-02-14 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cropbatch',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='farm_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('TRANSPORT_REQUESTED', 'Transport Requested'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED_BY_DISTRIBUTOR', 'Received by Distributor'), ('INSPECTED', 'Inspected'), ('LISTED_FOR_RETAIL', 'Listed for Retail'), ('SOLD', 'Sold')], default='CREATED', max_length=32),
        ),
    ]
