# Generated by Django 5.2.10 on 2026-02-14 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0002_cropbatch_current_owner_cropbatch_farm_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Batch Created'), ('TRANSPORT_REQUESTED', 'Transport Requested'), ('TRANSPORT_ACCEPTED', 'Transport Accepted'), ('TRANSPORT_STARTED', 'Transport Started'), ('DELIVERED', 'Delivered'), ('INSPECTED', 'Inspected'), ('INSPECTION_PASSED', 'Inspection Passed'), ('INSPECTION_FAILED', 'Inspection Failed'), ('LISTED', 'Listed for Retail'), ('SOLD', 'Sold to Consumer')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='supplychain.cropbatch')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['batch', '-timestamp'], name='supplychain_batch_i_8a02e7_idx')],
            },
        ),
    ]
