# Generated by Django 5.2.10 on 2026-02-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0003_batchevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Batch Created'), ('TRANSPORT_REQUESTED', 'Transport Requested'), ('TRANSPORT_ACCEPTED', 'Transport Accepted'), ('TRANSPORT_STARTED', 'Transport Started'), ('DELIVERED_TO_DISTRIBUTOR', 'Delivered to Distributor'), ('STORED', 'Stored by Distributor'), ('INSPECTED', 'Inspected'), ('INSPECTION_PASSED', 'Inspection Passed'), ('INSPECTION_FAILED', 'Inspection Failed'), ('TRANSPORT_REQUESTED_TO_RETAILER', 'Transport Requested to Retailer'), ('IN_TRANSIT_TO_RETAILER', 'In Transit to Retailer'), ('DELIVERED_TO_RETAILER', 'Delivered to Retailer'), ('LISTED', 'Listed for Retail'), ('SOLD', 'Sold to Consumer')], max_length=32),
        ),
        migrations.AlterField(
            model_name='cropbatch',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('TRANSPORT_REQUESTED', 'Transport Requested'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED_TO_DISTRIBUTOR', 'Delivered to Distributor'), ('STORED_BY_DISTRIBUTOR', 'Stored by Distributor'), ('TRANSPORT_REQUESTED_TO_RETAILER', 'Transport Requested to Retailer'), ('IN_TRANSIT_TO_RETAILER', 'In Transit to Retailer'), ('DELIVERED_TO_RETAILER', 'Delivered to Retailer'), ('LISTED', 'Listed for Sale'), ('SOLD', 'Sold')], default='CREATED', max_length=32),
        ),
    ]
