# Generated by Django 5.2.10 on 2026-02-15 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0004_alter_batchevent_event_type_alter_cropbatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchsplit',
            name='child_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_of_split', to='supplychain.cropbatch'),
        ),
        migrations.AddField(
            model_name='batchsplit',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='batchevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Batch Created'), ('TRANSPORT_REQUESTED', 'Transport Requested'), ('TRANSPORT_ACCEPTED', 'Transport Accepted'), ('TRANSPORT_STARTED', 'Transport Started'), ('DELIVERED_TO_DISTRIBUTOR', 'Delivered to Distributor'), ('STORED', 'Stored by Distributor'), ('INSPECTED', 'Inspected'), ('INSPECTION_PASSED', 'Inspection Passed'), ('INSPECTION_FAILED', 'Inspection Failed'), ('TRANSPORT_REQUESTED_TO_RETAILER', 'Transport Requested to Retailer'), ('IN_TRANSIT_TO_RETAILER', 'In Transit to Retailer'), ('DELIVERED_TO_RETAILER', 'Delivered to Retailer'), ('LISTED', 'Listed for Retail'), ('SOLD', 'Sold to Consumer'), ('TRANSPORT_REJECTED', 'Transport Rejected')], max_length=32),
        ),
        migrations.AlterField(
            model_name='cropbatch',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('TRANSPORT_REQUESTED', 'Transport Requested'), ('IN_TRANSIT_TO_DISTRIBUTOR', 'In Transit to Distributor'), ('DELIVERED_TO_DISTRIBUTOR', 'Delivered to Distributor'), ('STORED', 'Stored'), ('TRANSPORT_REQUESTED_TO_RETAILER', 'Transport Requested to Retailer'), ('IN_TRANSIT_TO_RETAILER', 'In Transit to Retailer'), ('DELIVERED_TO_RETAILER', 'Delivered to Retailer'), ('LISTED', 'Listed for Sale'), ('SOLD', 'Sold'), ('TRANSPORT_REJECTED', 'Transport Rejected')], default='CREATED', max_length=32),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(default='PENDING', max_length=32),
        ),
    ]
