# Generated by Django 5.2.10 on 2026-02-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0005_batchsplit_child_batch_batchsplit_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropbatch',
            name='is_child_batch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='parent_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_batches', to='supplychain.cropbatch'),
        ),
    ]
