# Generated by Django 5.2.10 on 2026-02-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0006_cropbatch_is_child_batch_cropbatch_parent_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropbatch',
            name='public_batch_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
