# Generated by Django 5.2.10 on 2026-02-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0007_cropbatch_public_batch_id_cropbatch_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropbatch',
            name='public_batch_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
