# Generated by Django 5.2.10 on 2026-02-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0010_alter_batchevent_event_type_alter_cropbatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropbatch',
            name='distributor_margin_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='farmer_base_price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='transporter_fee_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='batchevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Batch Created'), ('TRANSPORT_REQUESTED', 'Transport Requested'), ('TRANSPORT_ACCEPTED', 'Transport Accepted'), ('TRANSPORT_STARTED', 'Transport Started'), ('ARRIVED_AT_DISTRIBUTOR', 'Arrived at Distributor'), ('ARRIVAL_CONFIRMED_BY_DISTRIBUTOR', 'Arrival Confirmed by Distributor'), ('DELIVERED_TO_DISTRIBUTOR', 'Delivered to Distributor'), ('STORED', 'Stored by Distributor'), ('INSPECTED', 'Inspected'), ('INSPECTION_PASSED', 'Inspection Passed'), ('INSPECTION_FAILED', 'Inspection Failed'), ('TRANSPORT_REQUESTED_TO_RETAILER', 'Transport Requested to Retailer'), ('IN_TRANSIT_TO_RETAILER', 'In Transit to Retailer'), ('ARRIVED_AT_RETAILER', 'Arrived at Retailer'), ('ARRIVAL_CONFIRMED_BY_RETAILER', 'Arrival Confirmed by Retailer'), ('DELIVERED_TO_RETAILER', 'Delivered to Retailer'), ('LISTED', 'Listed for Retail'), ('SOLD', 'Sold to Consumer'), ('TRANSPORT_REJECTED', 'Transport Rejected'), ('SUSPENDED', 'Batch Suspended'), ('FULLY_SPLIT', 'Batch Fully Split')], max_length=32),
        ),
        migrations.AlterField(
            model_name='cropbatch',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('TRANSPORT_REQUESTED', 'Transport Requested'), ('IN_TRANSIT_TO_DISTRIBUTOR', 'In Transit to Distributor'), ('ARRIVED_AT_DISTRIBUTOR', 'Arrived at Distributor'), ('ARRIVAL_CONFIRMED_BY_DISTRIBUTOR', 'Arrival Confirmed by Distributor'), ('DELIVERED_TO_DISTRIBUTOR', 'Delivered to Distributor'), ('STORED', 'Stored'), ('TRANSPORT_REQUESTED_TO_RETAILER', 'Transport Requested to Retailer'), ('IN_TRANSIT_TO_RETAILER', 'In Transit to Retailer'), ('ARRIVED_AT_RETAILER', 'Arrived at Retailer'), ('ARRIVAL_CONFIRMED_BY_RETAILER', 'Arrival Confirmed by Retailer'), ('DELIVERED_TO_RETAILER', 'Delivered to Retailer'), ('LISTED', 'Listed for Sale'), ('SOLD', 'Sold'), ('TRANSPORT_REJECTED', 'Transport Rejected'), ('SUSPENDED', 'Suspended'), ('FULLY_SPLIT', 'Fully Split')], default='CREATED', max_length=32),
        ),
    ]
