# Generated by Django 5.2.10 on 2026-02-22 05:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0012_retaillisting_quantity_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionreport',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='inspection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='result',
            field=models.CharField(choices=[('PASS', 'Pass'), ('WARNING', 'Warning'), ('FAIL', 'Fail')], default='PASS', max_length=32),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='stage',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('transporter', 'Transporter'), ('distributor', 'Distributor'), ('retailer', 'Retailer')], default='farmer', max_length=32),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections_conducted', to='supplychain.stakeholderprofile'),
        ),
    ]
