# Generated by Django 5.2.10 on 2026-02-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0013_alter_inspectionreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrecord',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
