# Generated by Django 5.2.10 on 2026-02-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0014_kycrecord_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycrecord',
            name='notes',
        ),
    ]
