# Generated by Django 5.2.10 on 2026-02-24 13:23

import supplychain.db_file_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0015_remove_kycrecord_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropbatch',
            name='organic_certificate',
            field=supplychain.db_file_fields.DatabaseFileField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropbatch',
            name='qr_code_image',
            field=supplychain.db_file_fields.DatabaseImageField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropbatch',
            name='quality_test_report',
            field=supplychain.db_file_fields.DatabaseFileField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='report_file',
            field=supplychain.db_file_fields.DatabaseFileField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='document_file',
            field=supplychain.db_file_fields.DatabaseFileField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='delivery_proof',
            field=supplychain.db_file_fields.DatabaseFileField(blank=True, null=True),
        ),
    ]
