# Generated by Django 5.2.10 on 2026-02-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0016_alter_cropbatch_organic_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='stage',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('distributor', 'Distributor'), ('retailer', 'Retailer')], default='farmer', max_length=32),
        ),
    ]
