# Generated by Django 5.2.11 on 2026-02-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0017_alter_inspectionreport_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_role', models.CharField(choices=[('farmer', 'Farmer'), ('transporter', 'Transporter'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('consumer', 'Consumer'), ('admin', 'Admin')], max_length=32)),
                ('payee_role', models.CharField(choices=[('farmer', 'Farmer'), ('transporter', 'Transporter'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('consumer', 'Consumer'), ('admin', 'Admin')], max_length=32)),
                ('payment_type', models.CharField(choices=[('BATCH_PAYMENT', 'Batch Payment'), ('TRANSPORT_SHARE', 'Transport Share')], default='BATCH_PAYMENT', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DECLARED', 'Declared'), ('SETTLED', 'Settled')], default='PENDING', max_length=32)),
                ('payee_upi_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='supplychain.cropbatch')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='supplychain.stakeholderprofile')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to='supplychain.stakeholderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payer', 'status'], name='supplychain_payer_i_4c2a13_idx'), models.Index(fields=['payee', 'status'], name='supplychain_payee_i_3f5948_idx'), models.Index(fields=['batch', 'status'], name='supplychain_batch_i_4d6dec_idx')],
            },
        ),
    ]
