# Generated by Django 5.2.10 on 2026-02-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0018_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropbatch',
            name='current_phase',
            field=models.CharField(blank=True, choices=[('DISTRIBUTOR_PHASE', 'Distributor Phase'), ('RETAILER_PHASE', 'Retailer Phase')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='financial_status',
            field=models.CharField(blank=True, choices=[('PAYMENT_PENDING', 'Payment Pending'), ('DISTRIBUTOR_PHASE_SETTLED', 'Distributor Phase Settled'), ('RETAILER_PHASE_SETTLED', 'Retailer Phase Settled')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='phase',
            field=models.CharField(blank=True, choices=[('DISTRIBUTOR_PHASE', 'Distributor Phase'), ('RETAILER_PHASE', 'Retailer Phase')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_CONFIRMATION', 'Awaiting Confirmation'), ('SETTLED', 'Settled')], default='PENDING', max_length=32),
        ),
    ]
