# Generated by Django 5.2.10 on 2026-03-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0019_payment_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropbatch',
            name='distributor_payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='distributor_payment_to_farmer_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='distributor_payment_to_transporter_retailer_phase_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='distributor_payment_to_transporter_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='farmer_payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='farmer_payment_to_transporter_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='retailer_payment_to_distributor_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='retailer_payment_to_transporter_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='transporter_payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
