# Generated by Django 5.2.10 on 2026-03-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0020_cropbatch_distributor_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropbatch',
            name='anchor_tx_hash',
            field=models.CharField(blank=True, default='', max_length=66),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='anchored_snapshot_hash',
            field=models.CharField(blank=True, default='', max_length=66),
        ),
    ]
