class BatchStatus:
    CREATED = "CREATED"

    OFFERED_TO_DISTRIBUTOR = "OFFERED_TO_DISTRIBUTOR"
    ACCEPTED_BY_DISTRIBUTOR = "ACCEPTED_BY_DISTRIBUTOR"
    IN_TRANSIT_TO_DISTRIBUTOR = "IN_TRANSIT_TO_DISTRIBUTOR"
    AT_DISTRIBUTOR = "AT_DISTRIBUTOR"

    OFFERED_TO_RETAILER = "OFFERED_TO_RETAILER"
    ACCEPTED_BY_RETAILER = "ACCEPTED_BY_RETAILER"
    IN_TRANSIT_TO_RETAILER = "IN_TRANSIT_TO_RETAILER"
    AT_RETAILER = "AT_RETAILER"

    FOR_SALE = "FOR_SALE"
